CREATE TABLE TIP_ECHIPAMENT (
COD_TIP NUMBER(5) PRIMARY KEY,
TIP VARCHAR2(40) UNIQUE NOT NULL);

CREATE TABLE FURNIZORI (
COD_FURNIZOR NUMBER(5) PRIMARY KEY,
DENUMIRE VARCHAR2(60) NOT NULL, 
TELEFON VARCHAR2(15) UNIQUE NOT NULL,
ADRESA VARCHAR2(100) NOT NULL,
LOCALITATE VARCHAR2(40) NOT NULL);

--table clienti

CREATE TABLE CLIENTI (
COD_CLIENT NUMBER(5) PRIMARY KEY,
NUME VARCHAR2(30) NOT NULL,
COMPANIE VARCHAR2(30),
ADRESA VARCHAR2(100) NOT NULL,
LOCALITATE VARCHAR2(40) NOT NULL,
TELEFON VARCHAR2(15) UNIQUE NOT NULL,
EMAIL VARCHAR2(50) UNIQUE NOT NULL,
STATUS VARCHAR2(10) NOT NULL);

ALTER TABLE CLIENTI
ADD CONSTRAINT CK_CLIENTI_STATUS
CHECK (STATUS IN ('ACTIV','INACTIV'));

--produse it

CREATE TABLE PRODUSE_IT (
COD_PRODUS NUMBER(5) PRIMARY KEY,
COD_FURNIZOR NUMBER(5) NOT NULL,
PRODUCATOR VARCHAR2(20) NOT NULL,
GARANTIE NUMBER(2) NOT NULL, 
STOC NUMBER(4) NOT NULL,
CARACTERISTICI VARCHAR2(100) NOT NULL,
PRET DECIMAL(10,2) NOT NULL,
COD_TIP NUMBER(5) NOT NULL);

ALTER TABLE PRODUSE_IT
ADD CONSTRAINT CK_PRODUSE_PRET
CHECK (PRET > 0);

ALTER TABLE PRODUSE_IT
ADD CONSTRAINT CK_PRODUSE_STOC
CHECK (STOC >= 0);

ALTER TABLE PRODUSE_IT
ADD CONSTRAINT CK_PRODUSE_GARANTIE
CHECK (GARANTIE BETWEEN 0 AND 60);

ALTER TABLE PRODUSE_IT
ADD CONSTRAINT FK_PRODUSE_FURNIZOR
FOREIGN KEY (COD_FURNIZOR)
REFERENCES FURNIZORI (COD_FURNIZOR);

ALTER TABLE PRODUSE_IT
ADD CONSTRAINT FK_PRODUSE_TIP
FOREIGN KEY (COD_TIP)
REFERENCES TIP_ECHIPAMENT (COD_TIP);

ALTER TABLE PRODUSE_IT
MODIFY PRODUCATOR VARCHAR2(50);




--metoda de plata

CREATE TABLE METODA_PLATA(
COD_PLATA NUMBER(5) PRIMARY KEY,
METODA VARCHAR2(15) UNIQUE NOT NULL);

ALTER TABLE METODA_PLATA
ADD CONSTRAINT CK_METODA_PLATA
CHECK (METODA IN ('CARD','RAMBURS','TRANSFER'));

--TIP LIVRARE

CREATE TABLE TIP_LIVRARE(
COD_LIVRARE NUMBER(5) PRIMARY KEY,
METODA_LIVRARE VARCHAR2(15) UNIQUE NOT NULL);

ALTER TABLE TIP_LIVRARE
ADD CONSTRAINT CK_TIP_LIVRARE
CHECK( METODA_LIVRARE IN ('CURIER', 'EASYBOX', 'SHOWROOM'));

--TABEL STATUS COMANDA

CREATE TABLE STATUS_COMANDA (
  COD_STATUS NUMBER(5) PRIMARY KEY,
  STATUS     VARCHAR2(20) UNIQUE NOT NULL
);

ALTER TABLE STATUS_COMANDA
ADD CONSTRAINT CK_STATUS_COMANDA
CHECK (STATUS IN ('NOUA','IN_PROCESARE','EXPEDIATA','LIVRATA','ANULATA'));


--TABELA COMENZI

CREATE TABLE COMENZI(
COD_COMANDA NUMBER(5)PRIMARY KEY,
DATA_COMANDA DATE NOT NULL,
DATA_LIVRARE DATE NULL,
COD_LIVRARE NUMBER(5) NOT NULL,
COD_PLATA NUMBER(5) NOT NULL,
COD_CLIENT NUMBER(5) NOT NULL,
COD_STATUS_CURENT NUMBER(5) NOT NULL);

ALTER TABLE COMENZI
ADD CONSTRAINT CK_DATA_COMANDA
CHECK (DATA_LIVRARE IS NULL OR DATA_LIVRARE >= DATA_COMANDA);

ALTER TABLE COMENZI
ADD CONSTRAINT FK_CLIENTI_COD_LIVRARE
FOREIGN KEY (COD_LIVRARE)
REFERENCES TIP_LIVRARE (COD_LIVRARE);

ALTER TABLE COMENZI
ADD CONSTRAINT FK_CLIENTI_COD_PLATA
FOREIGN KEY (COD_PLATA)
REFERENCES METODA_PLATA (COD_PLATA);

ALTER TABLE COMENZI
ADD CONSTRAINT FK_CLIENTI_COD_CLIENT
FOREIGN KEY (COD_CLIENT)
REFERENCES CLIENTI (COD_CLIENT);

ALTER TABLE COMENZI
ADD CONSTRAINT FK_COMENZI_STATUS_CURENT
FOREIGN KEY (COD_STATUS_CURENT)
REFERENCES STATUS_COMANDA (COD_STATUS);

CREATE TABLE ISTORIC_STATUS_COMANDA (
  ID_ISTORIC     NUMBER(5) PRIMARY KEY,
  COD_COMANDA    NUMBER(5) NOT NULL,
  COD_STATUS     NUMBER(5) NOT NULL,
  DATA_SCHIMBARE DATE NOT NULL
);

ALTER TABLE ISTORIC_STATUS_COMANDA
ADD CONSTRAINT FK_ISTORIC_COMANDA
FOREIGN KEY (COD_COMANDA)
REFERENCES COMENZI (COD_COMANDA);

ALTER TABLE ISTORIC_STATUS_COMANDA
ADD CONSTRAINT FK_ISTORIC_STATUS
FOREIGN KEY (COD_STATUS)
REFERENCES STATUS_COMANDA (COD_STATUS);


--DETALII COMANDA

CREATE TABLE DETALII_COMANDA (
ID_DETALII NUMBER(5) PRIMARY KEY,
COD_COMANDA NUMBER(5) NOT NULL,
COD_PRODUS NUMBER(5) NOT NULL,
CANTITATE NUMBER(3) NOT NULL,
PRET_UNITAR DECIMAL(10,2) NOT NULL);

ALTER TABLE DETALII_COMANDA
ADD CONSTRAINT CK_DETALII_CANTITATE
CHECK(CANTITATE >= 1);

ALTER TABLE DETALII_COMANDA
ADD CONSTRAINT CK_DETALII_PRET
CHECK (PRET_UNITAR > 0);

ALTER TABLE DETALII_COMANDA
ADD CONSTRAINT UQ_DET_COMANDA_PRODUS
UNIQUE (COD_COMANDA, COD_PRODUS);

ALTER TABLE DETALII_COMANDA
ADD CONSTRAINT FK_DET_COMANDA
FOREIGN KEY (COD_COMANDA)
REFERENCES COMENZI (COD_COMANDA);

ALTER TABLE DETALII_COMANDA
ADD CONSTRAINT FK_DET_PRODUS
FOREIGN KEY (COD_PRODUS)
REFERENCES PRODUSE_IT (COD_PRODUS); 

--creare tabel promotii 

CREATE TABLE PROMOTII_PRODUSE(
COD_PROMOTIE NUMBER(5) PRIMARY KEY,
    DESCRIERE VARCHAR2(100),
    DISCOUNT NUMBER(3) );
    
ALTER TABLE PROMOTII_PRODUSE
ADD CONSTRAINT CK_PROMOTII_DISCOUNT
CHECK (DISCOUNT BETWEEN 0 AND 30);

DROP TABLE PROMOTII_PRODUSE;

--Exemple cu operatii de actualizare a datelor

--insert in TIP_ECHIPAMENT

INSERT INTO TIP_ECHIPAMENT (COD_TIP, TIP) VALUES (1, 'Laptop');
INSERT INTO TIP_ECHIPAMENT (COD_TIP, TIP) VALUES (2, 'Monitor');
INSERT INTO TIP_ECHIPAMENT (COD_TIP, TIP) VALUES (3, 'Tastatura');
INSERT INTO TIP_ECHIPAMENT (COD_TIP, TIP) VALUES (4, 'Mouse');
INSERT INTO TIP_ECHIPAMENT (COD_TIP, TIP) VALUES (5, 'Imprimanta');
INSERT INTO TIP_ECHIPAMENT (COD_TIP, TIP) VALUES (10, 'Scanner');

--insert in FURNIZORI

INSERT INTO FURNIZORI (COD_FURNIZOR, DENUMIRE, TELEFON, ADRESA, LOCALITATE) 
VALUES (1, 'Tech Distributors SRL', '0212345678', 'Str. Industriei nr. 45', 'Bucuresti');

INSERT INTO FURNIZORI (COD_FURNIZOR, DENUMIRE, TELEFON, ADRESA, LOCALITATE) 
VALUES (2, 'IT Solutions Import', '0213456789', 'Calea Victoriei nr. 120', 'Bucuresti');

INSERT INTO FURNIZORI (COD_FURNIZOR, DENUMIRE, TELEFON, ADRESA, LOCALITATE) 
VALUES (3, 'Euro Hardware SRL', '0314567890', 'Bd. Unirii nr. 88', 'Cluj-Napoca');

INSERT INTO FURNIZORI (COD_FURNIZOR, DENUMIRE, TELEFON, ADRESA, LOCALITATE) 
VALUES (4, 'Digital Wholesale', '0256789012', 'Str. Revolutiei nr. 15', 'Timisoara');

--insert in Clienti

INSERT INTO CLIENTI (COD_CLIENT, NUME, COMPANIE, ADRESA, LOCALITATE, TELEFON, EMAIL, STATUS)
VALUES(1, 'Tifrea Nicoleta - Corina', NULL, 'Bd. 1 Decembrie 1918 nr. 16', 'Bucuresti', '0745215829', 'tifrea_nicoleta@mail.com', 'ACTIV');

INSERT INTO CLIENTI (COD_CLIENT, NUME, COMPANIE, ADRESA, LOCALITATE, TELEFON, EMAIL, STATUS)
VALUES (2, 'Popescu Ion', 'SC Digital SRL', 'Str. Libertatii nr. 25', 'Bucuresti','0723456789', 'ion.popescu@digital.ro', 'ACTIV');

INSERT INTO CLIENTI (COD_CLIENT, NUME, COMPANIE, ADRESA, LOCALITATE, TELEFON, EMAIL, STATUS)
VALUES (3, 'Ionescu Maria', NULL, 'Bd. Independentei nr. 50', 'Cluj-Napoca', '0734567890', 'maria.ionescu@gmail.com', 'ACTIV');

INSERT INTO CLIENTI (COD_CLIENT, NUME, COMPANIE, ADRESA, LOCALITATE, TELEFON, EMAIL, STATUS)
VALUES (4, 'Georgescu Ana', 'Best Tech SRL', 'Calea Mosilor nr. 100', 'Bucuresti','0745678901', 'ana.georgescu@besttech.ro', 'INACTIV');

--INSERT INTO PRODUSE_IT 

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (1, 1, 'Lenovo', 24, 15, 'ThinkPad X1 Carbon, i7-1165G7, 16GB RAM, 512GB SSD', 5499.99, 1);

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (2, 1, 'Dell', 36, 8, 'XPS 15, i9-11900H, 32GB RAM, 1TB SSD, RTX 3050Ti', 8999.99, 1);

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (3, 2, 'LG', 24, 20, '27 inch, 4K UHD, IPS, 60Hz, HDR10', 1899.99, 2);

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (4, 2, 'Samsung', 36, 12, '32 inch Curved, WQHD, 144Hz, VA Panel', 2499.99, 2);

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (5, 3, 'Logitech', 12, 50, 'MX Keys, Wireless, Backlit, USB-C', 499.99, 3);

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (6, 3, 'Razer', 24, 30, 'BlackWidow V3, Mechanical, RGB, Green Switch', 699.99, 3);

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (7, 4, 'Logitech', 12, 45, 'MX Master 3S, Wireless, 8000 DPI, USB-C', 449.99, 4);

INSERT INTO PRODUSE_IT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
VALUES (8, 4, 'HP', 12, 10, 'LaserJet Pro M404dn, Monocrom, 38ppm, Duplex', 1299.99, 5);

-- insert in metoda de plata 

INSERT INTO METODA_PLATA (COD_PLATA, METODA) VALUES (1, 'CARD');
INSERT INTO METODA_PLATA (COD_PLATA, METODA) VALUES (2, 'RAMBURS');
INSERT INTO METODA_PLATA (COD_PLATA, METODA) VALUES (3, 'TRANSFER');


-- insert into TIP_LIVRARE
INSERT INTO TIP_LIVRARE (COD_LIVRARE, METODA_LIVRARE) VALUES (1, 'CURIER');
INSERT INTO TIP_LIVRARE (COD_LIVRARE, METODA_LIVRARE) VALUES (2, 'EASYBOX');
INSERT INTO TIP_LIVRARE (COD_LIVRARE, METODA_LIVRARE) VALUES (3, 'SHOWROOM');

--INSERT INTO STATUS COMANDA

INSERT INTO STATUS_COMANDA (COD_STATUS, STATUS) VALUES (1, 'NOUA');
INSERT INTO STATUS_COMANDA (COD_STATUS, STATUS) VALUES (2, 'IN_PROCESARE');
INSERT INTO STATUS_COMANDA (COD_STATUS, STATUS) VALUES (3, 'EXPEDIATA');
INSERT INTO STATUS_COMANDA (COD_STATUS, STATUS) VALUES (4, 'LIVRATA');
INSERT INTO STATUS_COMANDA (COD_STATUS, STATUS) VALUES (5, 'ANULATA');

-- INSERT INTO COMENZI

INSERT INTO COMENZI (COD_COMANDA, DATA_COMANDA, DATA_LIVRARE, COD_LIVRARE, COD_PLATA, COD_CLIENT, COD_STATUS_CURENT)
VALUES (1, TO_DATE('15-12-2024', 'DD-MM-YYYY'), TO_DATE('18-12-2024', 'DD-MM-YYYY'), 1, 1, 1, 4);

INSERT INTO COMENZI (COD_COMANDA, DATA_COMANDA, DATA_LIVRARE, COD_LIVRARE, COD_PLATA, COD_CLIENT, COD_STATUS_CURENT)
VALUES (2, TO_DATE('20-12-2024', 'DD-MM-YYYY'), NULL, 2, 2, 2, 2);

INSERT INTO COMENZI (COD_COMANDA, DATA_COMANDA, DATA_LIVRARE, COD_LIVRARE, COD_PLATA, COD_CLIENT, COD_STATUS_CURENT)
VALUES (3, TO_DATE('22-12-2024', 'DD-MM-YYYY'), TO_DATE('25-12-2024', 'DD-MM-YYYY'), 1, 3, 3, 4);

INSERT INTO COMENZI (COD_COMANDA, DATA_COMANDA, DATA_LIVRARE, COD_LIVRARE, COD_PLATA, COD_CLIENT, COD_STATUS_CURENT)
VALUES (4, TO_DATE('05-01-2025', 'DD-MM-YYYY'), NULL, 3, 1, 1, 1);

INSERT INTO COMENZI (COD_COMANDA, DATA_COMANDA, DATA_LIVRARE, COD_LIVRARE, COD_PLATA, COD_CLIENT, COD_STATUS_CURENT)
     VALUES (99, SYSDATE, NULL, 1, 1, 1, 5);


-- INSERT IINTO DETALII COMANDA 

--  COMANDA 1
INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (1, 1, 1, 1, 5499.99);

INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (2, 1, 5, 1, 499.99);

--COMANDA 2 
INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (3, 2, 3, 2, 1899.99);

INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (4, 2, 7, 1, 449.99);

--  comanda 3
INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (5, 3, 2, 1, 8999.99);

INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (6, 3, 4, 1, 2499.99);

-- COMANDA 4
INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (7, 4, 6, 2, 699.99);

INSERT INTO DETALII_COMANDA (ID_DETALII, COD_COMANDA, COD_PRODUS, CANTITATE, PRET_UNITAR)
VALUES (8, 4, 8, 1, 1299.99);

--INSERT INTO ISTORIC_STATUS_COMANDA

-- Istoric pentru comanda 1 
INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (1, 1, 1, TO_DATE('15-12-2024 10:30', 'DD-MM-YYYY HH24:MI'));

INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (2, 1, 2, TO_DATE('15-12-2024 14:00', 'DD-MM-YYYY HH24:MI'));

INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (3, 1, 3, TO_DATE('16-12-2024 09:00', 'DD-MM-YYYY HH24:MI'));

INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (4, 1, 4, TO_DATE('18-12-2024 15:30', 'DD-MM-YYYY HH24:MI'));

-- Istoric pentru comanda 2
INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (5, 2, 1, TO_DATE('20-12-2024 11:00', 'DD-MM-YYYY HH24:MI'));

INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (6, 2, 2, TO_DATE('20-12-2024 16:30', 'DD-MM-YYYY HH24:MI'));

-- Istoric pentru comanda 3
INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (7, 3, 1, TO_DATE('22-12-2024 09:15', 'DD-MM-YYYY HH24:MI'));

INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (8, 3, 2, TO_DATE('22-12-2024 12:00', 'DD-MM-YYYY HH24:MI'));

INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (9, 3, 4, TO_DATE('25-12-2024 14:30', 'DD-MM-YYYY HH24:MI'));

-- Istoric pentru comanda 4
INSERT INTO ISTORIC_STATUS_COMANDA (ID_ISTORIC, COD_COMANDA, COD_STATUS, DATA_SCHIMBARE)
VALUES (10, 4, 1, TO_DATE('05-01-2025 10:00', 'DD-MM-YYYY HH24:MI'));






SELECT *
FROM CLIENTI
WHERE NUME = 'Tifrea Nicoleta - Corina';

UPDATE PRODUSE_IT 
     SET PRET = PRET * 1.1 
     WHERE COD_PRODUS = 1;
     
     UPDATE CLIENTI 
     SET STATUS = 'INACTIV' 
     WHERE NUME = 'Popescu Ion';
     
     UPDATE FURNIZORI 
     SET LOCALITATE = 'Ilfov' 
     WHERE DENUMIRE = 'IT Solutions Import';
     
     UPDATE PRODUSE_IT 
     SET GARANTIE = GARANTIE + 12 
     WHERE COD_FURNIZOR = (SELECT COD_FURNIZOR FROM FURNIZORI WHERE DENUMIRE = 'Tech Distributors SRL');
     
     DELETE FROM PRODUSE_IT 
     WHERE COD_PRODUS NOT IN (SELECT COD_PRODUS FROM DETALII_COMANDA);
     --Să se utilizeze operația MERGE pentru a actualiza datele unui produs sau a-l insera dacă acesta nu există (MERGE):
     
      MERGE INTO PRODUSE_IT p
     USING (SELECT 5 as COD, 3 as FURN, 20 as STOC_NOU FROM dual) src
     ON (p.COD_PRODUS = src.COD)
     WHEN MATCHED THEN
        UPDATE SET p.STOC = p.STOC + src.STOC_NOU
     WHEN NOT MATCHED THEN
        INSERT (COD_PRODUS, COD_FURNIZOR, PRODUCATOR, GARANTIE, STOC, CARACTERISTICI, PRET, COD_TIP)
        VALUES (5, 3, 'Logitech', 12, 20, 'MX Keys Wireless', 499.99, 3);
  
  --sa se utilizeze operatia merge pentru actualizarea globala a preturilor si stocurilor 'IT Solutions Import'
  
   MERGE INTO PRODUSE_IT p
     USING (SELECT 3 as COD, 1950.00 as PRET_NOU, 5 as STOC_ADITIV FROM dual) src
     ON (p.COD_PRODUS = src.COD)
     WHEN MATCHED THEN
        UPDATE SET p.PRET = src.PRET_NOU, 
                   p.STOC = p.STOC + src.STOC_ADITIV;

     
--Sa se afiseze produsele cu pretul intre 500 si 300 de lei si garantie mai mare sau egala cu 24 de luni

SELECT COD_PRODUS, PRODUCATOR, CARACTERISTICI, PRET, GARANTIE
FROM PRODUSE_IT
WHERE PRET BETWEEN 500 AND 3000
  AND GARANTIE >= 24
ORDER BY PRET DESC;

--	Sa se afiseze clientii din Bucuresti si Cluj-Napoca care nu au companie asociata si au nume care contine litera ‘i’

SELECT NUME, LOCALITATE, EMAIL, COMPANIE
FROM CLIENTI
WHERE COMPANIE IS NULL
  AND LOCALITATE IN ('Bucuresti', 'Cluj-Napoca')
  AND NUME LIKE '%i%';

--Sa se afiseze toate produsele impreuna cu informatiile furnizorilor lor

SELECT p.COD_PRODUS, p.PRODUCATOR, p.PRET, p.STOC,
       f.DENUMIRE AS FURNIZOR, f.LOCALITATE AS LOC_FURNIZOR
FROM PRODUSE_IT p
INNER JOIN FURNIZORI f ON p.COD_FURNIZOR = f.COD_FURNIZOR
ORDER BY p.PRET DESC;

--sa se afiseze afiseze numarul de produse si pretul mediu pentru fiecare producator in parte

SELECT PRODUCATOR, COUNT(*) AS NR_PRODUSE, AVG(PRET) AS PRET_MEDIU
FROM PRODUSE_IT
GROUP BY PRODUCATOR;

--	Sa se afiseze producatorii care au un stoc total de peste 20 de unitati cumulate

SELECT PRODUCATOR, SUM(STOC) AS STOC_TOTAL
FROM PRODUSE_IT
GROUP BY PRODUCATOR
HAVING SUM(STOC) > 20;

-- Sa se afiseze codul comenzii si data acesteia (zi-luna-an) filtrand doar comenzile din anul curent
SELECT COD_COMANDA, TO_CHAR(DATA_COMANDA, 'Day, DD Month YYYY') AS DATA_DETALIATA
FROM COMENZI
WHERE EXTRACT(YEAR FROM DATA_COMANDA) = EXTRACT(YEAR FROM SYSDATE);

-- 	Sa se afiseze primele 3 litere ale producatorului si denumirea compmaniei clientului (daca aceasta lipseste se va afisa ‘Persoana Fizica’)

SELECT SUBSTR(PRODUCATOR, 1, 3) AS COD_PROD, NVL(COMPANIE, 'Persoana Fizica') AS ENTITATE
FROM PRODUSE_IT, CLIENTI;

--	Sa se clasifice produsele in funcție de pret și sa se traduca codul de tip echipament.
SELECT PRODUCATOR, PRET,
       CASE WHEN PRET > 3000 THEN 'Premium' ELSE 'Standard' END AS CATEGORIE,
       DECODE(COD_TIP, 1, 'Laptop', 2, 'Monitor', 3, 'Periferic', 'Altul') AS TIP_ECHIPAMENT
FROM PRODUSE_IT;

-- Sa se afiseze o lista cu toate localitatile in care avem prezenta (clienti sau furnizori), eliminand duplicatele.
SELECT LOCALITATE FROM CLIENTI
UNION
SELECT LOCALITATE FROM FURNIZORI;

--	Sa se afiseze ID-urile clientilor care s-au inregistrat, dar care nu au plasat inca nici o comanda.

SELECT COD_CLIENT FROM CLIENTI
MINUS
SELECT COD_CLIENT FROM COMENZI;

--	Sa se afiseze toate produsele care au pretul mai mare decat media preturilor tuturor preturilor din tabela


SELECT * FROM PRODUSE_IT
WHERE PRET > (SELECT AVG(PRET) FROM PRODUSE_IT);

--	Sa se afiseze numele fiecarui furnizor si umarul de produse pe care acesta le furnizeaza

SELECT f.DENUMIRE, 
       (SELECT COUNT(*) FROM PRODUSE_IT p WHERE p.COD_FURNIZOR = f.COD_FURNIZOR) AS NR_PRODUSE
FROM FURNIZORI f;


CREATE VIEW V_STOC_CRITIC AS 
SELECT PRODUCATOR, CARACTERISTICI, STOC FROM PRODUSE_IT WHERE STOC < 10;

CREATE INDEX IDX_PRODUCATOR ON PRODUSE_IT(PRODUCATOR);

--	Sa se afiseze toti clientii si data comenzii lor, incluzand clientii care nu au comandat nimic pana acum

SELECT c.NUME, com.DATA_COMANDA
FROM CLIENTI c
LEFT OUTER JOIN COMENZI com ON c.COD_CLIENT = com.COD_CLIENT;


--Sa se afiseze produsele cu evaluare stoc (critic, mediu, bun) si recomandare de aprovizionare


SELECT PRODUCATOR, CARACTERISTICI, STOC, PRET,
       CASE 
           WHEN STOC = 0 THEN 'STOC EPUIZAT'
           WHEN STOC < 10 THEN 'STOC CRITIC - Comanda urgenta'
           WHEN STOC BETWEEN 10 AND 20 THEN 'STOC MEDIU - Monitorizare'
           ELSE 'STOC SUFICIENT'
       END AS STATUS_STOC,
       CASE 
           WHEN STOC < 10 THEN PRET * 20
           WHEN STOC < 20 THEN PRET * 10
           ELSE 0
       END AS VALOARE_REAPROVIZIONARE
FROM PRODUSE_IT
ORDER BY STOC ASC;
